# Generated by Django 4.0.3 on 2023-01-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Economy', 'ECONOMY'), ('Standard', 'STANDARD'), ('SUV', 'PREMIUM SUV'), ('Signature Series', 'SIGNATURE SERIES')], max_length=100, null=True)),
                ('rate', models.IntegerField()),
                ('licensenm', models.CharField(max_length=100)),
                ('available', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='Yes', max_length=100)),
                ('available_at', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemain.dealerlocation')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('type', models.CharField(choices=[('Economy', 'ECONOMY'), ('Standard', 'STANDARD'), ('SUV', 'PREMIUM SUV'), ('Signature Series', 'SIGNATURE SERIES')], max_length=100, null=True)),
                ('days_rented', models.IntegerField(null=True)),
                ('order_total', models.IntegerField(null=True)),
                ('reservation_status', models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_pickup_location', to='sitemain.dealerlocation')),
                ('return_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_return_location', to='sitemain.dealerlocation')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemain.vehicle')),
            ],
        ),
    ]
