# Generated by Django 4.0.3 on 2023-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemain', '0004_remove_vehicle_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Paid', 'Paid'), ('Close', 'Close'), ('Canceled', 'Canceled')], default='Open', max_length=100),
        ),
    ]
